language: perl
perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
env:
    - "RELEASE_TESTING=1"
install:
    - "cpanm -n Test::CheckManifest Test::Pod Test::Pod::Coverage"
    - "cpanm -n --installdeps ."

